apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    # --- ИЗМЕНИ ВОТ ЭТУ СТРОКУ ---
    # Добавляем "before-hook-creation". Это значит: "Удали старую джобу перед созданием новой"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  template:
    spec:
      restartPolicy: OnFailure
      # Добавляем наш ожидальщик базы, чтобы скрипт не упал, если база еще греется
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command: ['sh', '-c', "until nc -z {{ .Release.Name }}-postgres 5432; do echo waiting for postgres; sleep 2; done"]

      containers:
        - name: db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Выполняем обе команды последовательно
          command: ["sh", "-c", "python ./models/model.py && ./demo_init.sh"]

          # Обязательно передаем переменные, чтобы скрипт знал, где база
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets