apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          resources:
{{ toYaml .Values.resources.main | indent 12 }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-pass
                  key: RABBITMQ_DEFAULT_USER
          envFrom:
            - secretRef:
                name: rabbitmq-pass
          startupProbe:
            exec:
              command: [ "rabbitmq-diagnostics", "-q", "ping" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            exec:
              command: [ "rabbitmq-diagnostics", "-q", "ping" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "rabbitmq-diagnostics", "-q", "check_running" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

