apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  # Данные для RabbitMQ
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password }}

  RABBIT_USER: {{ .Values.rabbitmq.auth.username }}
  RABBIT_PASSWORD: {{ .Values.rabbitmq.auth.password }}

  # Данные для Postgres
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password }}

  # Ключи приложения
  SECRET_KEY: "123123"

  # --- ВОТ ЗДЕСЬ БЫЛА ОШИБКА ---
  # Мы формируем правильную строку подключения с новым хостом: {{ .Release.Name }}-postgres
  # ==========================================
  # 1. ПЕРЕМЕННЫЕ ДЛЯ САМОГО POSTGRES (Вернули их назад)
  # ==========================================
  CONNECTION_URI: "postgresql+psycopg2://{{ .Values.postgres.auth.user }}:{{ .Values.postgres.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.auth.db }}"