apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-data
spec:
  # В локальном K3d обычно используется standard или local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi