apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources.main | indent 12 }}
          command: ["streamlit", "run", "./webui.py", "--server.port=8501", "--server.address=0.0.0.0"]
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          volumeMounts:
            # Монтируем наш диск в папку /data
            - mountPath: /data
              name: shared-data-volume
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - main-app
                      - worker
                      - webui
              topologyKey: "kubernetes.io/hostname"

          # Тут можно добавить livenessProbe / readinessProbe
      volumes:
        # Объявляем диск, ссылаясь на созданный PVC
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-data